/**
 *
 * $Id$
 */
package SPLmodel.validation;

import SPLmodel.Feature;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link SPLmodel.CoreAsset}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CoreAssetValidator {
	boolean validate();

	boolean validateIdCoreAsset(String value);
	boolean validateName(String value);
	boolean validatePath(String value);
	boolean validateContent(String value);
	boolean validateSize(int value);
	boolean validateMappedTo(EList<Feature> value);
}
