/**
 *
 * $Id$
 */
package SPLmodel.validation;

import SPLmodel.CoreAsset;
import SPLmodel.Feature;
import SPLmodel.ProductPortfolio;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link SPLmodel.CoreAssetBaseline}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CoreAssetBaselineValidator {
	boolean validate();

	boolean validateIdBaseline(String value);
	boolean validateReleaseDate(String value);
	boolean validateProductPortfolio(ProductPortfolio value);
	boolean validateCoreasset(EList<CoreAsset> value);
	boolean validateFeature(EList<Feature> value);
}
