/**
 *
 * $Id$
 */
package SPLmodel.validation;

import SPLmodel.CoreAsset;
import SPLmodel.ProductAsset;

/**
 * A sample validator interface for {@link SPLmodel.CustomizationEffort}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CustomizationEffortValidator {
	boolean validate();

	boolean validateIdCustomization(int value);
	boolean validateAdded_LOCs(int value);
	boolean validateDeleted_LOCs(int value);
	boolean validateCustCA(CoreAsset value);
	boolean validateProductasset(ProductAsset value);
}
