/**
 *
 * $Id$
 */
package SPLmodel.validation;

import SPLmodel.CoreAsset;
import SPLmodel.CoreAssetBaseline;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link SPLmodel.Feature}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FeatureValidator {
	boolean validate();

	boolean validateIdFeature(String value);
	boolean validateName(String value);
	boolean validateCoreassetbaseline(EList<CoreAssetBaseline> value);
	boolean validateCoreAssets(EList<CoreAsset> value);
}
