/**
 *
 * $Id$
 */
package SPLmodel.validation;

import SPLmodel.ProductRelease;

/**
 * A sample validator interface for {@link SPLmodel.ProductAsset}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ProductAssetValidator {
	boolean validate();

	boolean validateIdAsset(String value);
	boolean validateName(String value);
	boolean validatePath(String value);
	boolean validateContent(String value);
	boolean validateSize(int value);
	boolean validateFromRelease(ProductRelease value);
}
