/**
 *
 * $Id$
 */
package SPLmodel.validation;

import SPLmodel.ProductPortfolio;
import SPLmodel.ProductRelease;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link SPLmodel.Product}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ProductValidator {
	boolean validate();

	boolean validateIdProduct(String value);
	boolean validateName(String value);
	boolean validateInPortfolio(ProductPortfolio value);
	boolean validateReleases(EList<ProductRelease> value);
}
