/**
 *
 * $Id$
 */
package SPLmodel.validation;

import SPLmodel.Product;
import SPLmodel.ProductAsset;

import java.util.Date;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link SPLmodel.ProductRelease}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ProductReleaseValidator {
	boolean validate();

	boolean validateIdRelease(String value);
	boolean validateReleaseDate(String value);

	boolean validateReleaseDate(Date value);
	boolean validateProduct(Product value);
	boolean validateProductasset(EList<ProductAsset> value);
}
