/**
 *
 * $Id$
 */
package SPLmodel.validation;

import SPLmodel.CoreAssetBaseline;
import SPLmodel.Product;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link SPLmodel.ProductPortfolio}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ProductPortfolioValidator {
	boolean validate();

	boolean validateIdProductPortfolio(String value);
	boolean validateDerivedFrom(CoreAssetBaseline value);
	boolean validateProducts(EList<Product> value);
}
