<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="SPLmodel" nsURI="customs" nsPrefix="SPLmodel">
  <eClassifiers xsi:type="ecore:EClass" name="SPL">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idSPL" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baselines" upperBound="-1"
        eType="#//CoreAssetBaseline" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="portfolio" upperBound="-1"
        eType="#//ProductPortfolio" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoreAssetBaseline">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idBaseline" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ReleaseDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="productPortfolio" eType="#//ProductPortfolio"
        eOpposite="#//ProductPortfolio/derivedFrom"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coreasset" upperBound="-1"
        eType="#//CoreAsset" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//Feature" eOpposite="#//Feature/inBaseline"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idFeature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inBaseline" upperBound="-1"
        eType="#//CoreAssetBaseline" eOpposite="#//CoreAssetBaseline/features"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coreAssets" lowerBound="1"
        upperBound="-1" eType="#//CoreAsset" eOpposite="#//CoreAsset/mappedTo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CoreAsset">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idCoreAsset" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mappedTo" lowerBound="1"
        upperBound="-1" eType="#//Feature" eOpposite="#//Feature/coreAssets"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CustomizationEffort">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idCustomization" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="added_LOCs" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deleted_LOCs" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="custCA" eType="#//CoreAsset"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="productasset" eType="#//ProductAsset"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProductPortfolio">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idProductPortfolio" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="derivedFrom" eType="#//CoreAssetBaseline"
        eOpposite="#//CoreAssetBaseline/productPortfolio"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="products" upperBound="-1"
        eType="#//Product" eOpposite="#//Product/inPortfolio"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Product">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idProduct" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inPortfolio" eType="#//ProductPortfolio"
        eOpposite="#//ProductPortfolio/products"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="releases" upperBound="-1"
        eType="#//ProductRelease" eOpposite="#//ProductRelease/product"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProductRelease">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idRelease" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="releaseDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="product" eType="#//Product"
        eOpposite="#//Product/releases"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="productasset" upperBound="-1"
        eType="#//ProductAsset" eOpposite="#//ProductAsset/fromRelease"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProductAsset">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idAsset" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fromRelease" eType="#//ProductRelease"
        eOpposite="#//ProductRelease/productasset"/>
  </eClassifiers>
</ecore:EPackage>
