//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.07 at 02:03:52 PM CEST 
//


package customDiff.utils.featuremodel;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the test.java package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Consulmodel_QNAME = new QName("http://www.pure-systems.com/consul/model", "consulmodel");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: test.java
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ConsulmodelType }
     * 
     */
    public ConsulmodelType createConsulmodelType() {
        return new ConsulmodelType();
    }

    /**
     * Create an instance of {@link RelationType }
     * 
     */
    public RelationType createRelationType() {
        return new RelationType();
    }

    /**
     * Create an instance of {@link HeadType }
     * 
     */
    public HeadType createHeadType() {
        return new HeadType();
    }

    /**
     * Create an instance of {@link MimedescType }
     * 
     */
    public MimedescType createMimedescType() {
        return new MimedescType();
    }

    /**
     * Create an instance of {@link DescType }
     * 
     */
    public DescType createDescType() {
        return new DescType();
    }

    /**
     * Create an instance of {@link TargetType }
     * 
     */
    public TargetType createTargetType() {
        return new TargetType();
    }

    /**
     * Create an instance of {@link RelationsType }
     * 
     */
    public RelationsType createRelationsType() {
        return new RelationsType();
    }

    /**
     * Create an instance of {@link ElementsType }
     * 
     */
    public ElementsType createElementsType() {
        return new ElementsType();
    }

    /**
     * Create an instance of {@link ConstantType }
     * 
     */
    public ConstantType createConstantType() {
        return new ConstantType();
    }

    /**
     * Create an instance of {@link PropertyType }
     * 
     */
    public PropertyType createPropertyType() {
        return new PropertyType();
    }

    /**
     * Create an instance of {@link PropertiesType }
     * 
     */
    public PropertiesType createPropertiesType() {
        return new PropertiesType();
    }

    /**
     * Create an instance of {@link VnameType }
     * 
     */
    public VnameType createVnameType() {
        return new VnameType();
    }

    /**
     * Create an instance of {@link ElementType }
     * 
     */
    public ElementType createElementType() {
        return new ElementType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConsulmodelType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.pure-systems.com/consul/model", name = "consulmodel")
    public JAXBElement<ConsulmodelType> createConsulmodel(ConsulmodelType value) {
        return new JAXBElement<ConsulmodelType>(_Consulmodel_QNAME, ConsulmodelType.class, null, value);
    }

}
