//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.07 at 02:03:52 PM CEST 
//


package customDiff.utils.featuremodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for vnameType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="vnameType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="mimedesc" type="{http://www.pure-systems.com/consul/model}mimedescType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "vnameType", propOrder = {
    "mimedesc"
})
public class VnameType {

    @XmlElement(required = true)
    protected MimedescType mimedesc;

    /**
     * Gets the value of the mimedesc property.
     * 
     * @return
     *     possible object is
     *     {@link MimedescType }
     *     
     */
    public MimedescType getMimedesc() {
        return mimedesc;
    }

    /**
     * Sets the value of the mimedesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link MimedescType }
     *     
     */
    public void setMimedesc(MimedescType value) {
        this.mimedesc = value;
    }

}
