-- MySQL Script generated by MySQL Workbench
-- Mon Oct 23 19:18:59 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema olapCustoms
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema olapCustoms
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `olapCustoms` DEFAULT CHARACTER SET utf8 ;
USE `olapCustoms` ;

-- -----------------------------------------------------
-- Table `olapCustoms`.`core_asset`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olapCustoms`.`core_asset` (
  `id_coreasset` INT NOT NULL,
  `name` VARCHAR(200) NULL,
  `path` VARCHAR(200) NULL,
  `size` INT NULL,
  `isNewAsset` INT NULL,
  `content` LONGTEXT NULL,
  PRIMARY KEY (`id_coreasset`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olapCustoms`.`feature_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olapCustoms`.`feature_group` (
  `id_feature_group` INT NOT NULL,
  PRIMARY KEY (`id_feature_group`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olapCustoms`.`variation_point`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olapCustoms`.`variation_point` (
  `id_variationpoint` INT NOT NULL,
  `expression` LONGTEXT NULL,
  `id_coreasset` INT NOT NULL,
  `id_feature_group` INT NULL,
  PRIMARY KEY (`id_variationpoint`),
  INDEX `fk_ProductAssetVP_ProductAsset1_idx` (`id_coreasset` ASC),
  INDEX `fk_VariationPoint_Feature_group1_idx` (`id_feature_group` ASC),
  CONSTRAINT `fk_ProductAssetVP_ProductAsset1`
    FOREIGN KEY (`id_coreasset`)
    REFERENCES `olapCustoms`.`core_asset` (`id_coreasset`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VariationPoint_Feature_group1`
    FOREIGN KEY (`id_feature_group`)
    REFERENCES `olapCustoms`.`feature_group` (`id_feature_group`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olapCustoms`.`developer_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olapCustoms`.`developer_group` (
  `id_developer_group` INT NOT NULL,
  PRIMARY KEY (`id_developer_group`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olapCustoms`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olapCustoms`.`product` (
  `id_product` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id_product`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olapCustoms`.`product_release`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olapCustoms`.`product_release` (
  `id_productrelease` INT NOT NULL,
  `name` VARCHAR(200) NULL,
  `date` DATETIME NULL,
  `commits_set` LONGTEXT NULL,
  `id_product` INT NOT NULL,
  PRIMARY KEY (`id_productrelease`),
  INDEX `fk_ProductRelease_Product1_idx` (`id_product` ASC),
  CONSTRAINT `fk_ProductRelease_Product1`
    FOREIGN KEY (`id_product`)
    REFERENCES `olapCustoms`.`product` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olapCustoms`.`customization_fact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olapCustoms`.`customization_fact` (
  `id_customization` INT NOT NULL AUTO_INCREMENT,
  `lines_added` INT NULL,
  `lines_deleted` INT NULL,
  `custom_diff` LONGTEXT NULL,
  `commit_set` LONGTEXT NULL,
  `message_set` LONGTEXT NULL,
  `greater_diff` LONGTEXT NULL,
  `id_variationpoint` INT NOT NULL,
  `id_developer_group` INT NOT NULL,
  `id_productrelease` INT NOT NULL,
  PRIMARY KEY (`id_customization`),
  INDEX `fk_Customization_ProductAssetVP_idx` (`id_variationpoint` ASC),
  INDEX `fk_CustomizationFact_developer_group1_idx` (`id_developer_group` ASC),
  INDEX `fk_CustomizationFact_ProductRelease1_idx` (`id_productrelease` ASC),
  CONSTRAINT `fk_Customization_ProductAssetVP`
    FOREIGN KEY (`id_variationpoint`)
    REFERENCES `olapCustoms`.`variation_point` (`id_variationpoint`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CustomizationFact_developer_group1`
    FOREIGN KEY (`id_developer_group`)
    REFERENCES `olapCustoms`.`developer_group` (`id_developer_group`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CustomizationFact_ProductRelease1`
    FOREIGN KEY (`id_productrelease`)
    REFERENCES `olapCustoms`.`product_release` (`id_productrelease`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olapCustoms`.`developer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olapCustoms`.`developer` (
  `id_developer` INT NOT NULL,
  `name` VARCHAR(200) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id_developer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olapCustoms`.`feature`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olapCustoms`.`feature` (
  `id_feature` VARCHAR(200) NOT NULL,
  `name` VARCHAR(200) NULL,
  PRIMARY KEY (`id_feature`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olapCustoms`.`feature_bridge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olapCustoms`.`feature_bridge` (
  `id_feature_group` INT NOT NULL,
  `id_feature` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_feature_group`, `id_feature`),
  INDEX `fk_Feature_group_has_Feature_Feature1_idx` (`id_feature` ASC),
  INDEX `fk_Feature_group_has_Feature_Feature_group1_idx` (`id_feature_group` ASC),
  CONSTRAINT `fk_Feature_group_has_Feature_Feature_group1`
    FOREIGN KEY (`id_feature_group`)
    REFERENCES `olapCustoms`.`feature_group` (`id_feature_group`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Feature_group_has_Feature_Feature1`
    FOREIGN KEY (`id_feature`)
    REFERENCES `olapCustoms`.`feature` (`id_feature`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olapCustoms`.`developer_bridge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olapCustoms`.`developer_bridge` (
  `id_developer_group` INT NOT NULL,
  `id_developer` INT NOT NULL,
  PRIMARY KEY (`id_developer_group`, `id_developer`),
  INDEX `fk_developer_bridge_developer_group1_idx` (`id_developer_group` ASC),
  INDEX `fk_developer_bridge_Developer1_idx` (`id_developer` ASC),
  CONSTRAINT `fk_developer_bridge_developer_group1`
    FOREIGN KEY (`id_developer_group`)
    REFERENCES `olapCustoms`.`developer_group` (`id_developer_group`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_developer_bridge_Developer1`
    FOREIGN KEY (`id_developer`)
    REFERENCES `olapCustoms`.`developer` (`id_developer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
