-- MySQL Script generated by MySQL Workbench
-- Tue Sep  5 18:22:21 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema olapCustoms
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema olapCustoms
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `olapCustoms` DEFAULT CHARACTER SET utf8 ;
USE `olapCustoms` ;

-- -----------------------------------------------------
-- Table `olapCustoms`.`ProductAsset`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olapCustoms`.`ProductAsset` (
  `idProductAsset` INT NOT NULL,
  `content` VARCHAR(200) NULL,
  `size` INT NULL,
  `name` VARCHAR(200) NULL,
  `path` VARCHAR(200) NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`idProductAsset`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olapCustoms`.`ProductAssetVP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olapCustoms`.`ProductAssetVP` (
  `idPV` INT NOT NULL,
  `expression` VARCHAR(200) NULL,
  `initLine` INT NULL,
  `finalLine` INT NULL,
  `ProductAsset_idProductAsset` INT NOT NULL,
  PRIMARY KEY (`idPV`),
  INDEX `fk_ProductAssetVP_ProductAsset1_idx` (`ProductAsset_idProductAsset` ASC),
  CONSTRAINT `fk_ProductAssetVP_ProductAsset1`
    FOREIGN KEY (`ProductAsset_idProductAsset`)
    REFERENCES `olapCustoms`.`ProductAsset` (`idProductAsset`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olapCustoms`.`CoreAssetBaseline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olapCustoms`.`CoreAssetBaseline` (
  `idCoreAssetBaseline` INT NOT NULL,
  `name` VARCHAR(200) NULL,
  PRIMARY KEY (`idCoreAssetBaseline`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olapCustoms`.`ProductRelease`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olapCustoms`.`ProductRelease` (
  `idProductRelease` INT NOT NULL,
  `name` VARCHAR(200) NULL,
  `CoreAssetBaseline_idCoreAssetBaseline` INT NOT NULL,
  PRIMARY KEY (`idProductRelease`),
  INDEX `fk_ProductRelease_CoreAssetBaseline1_idx` (`CoreAssetBaseline_idCoreAssetBaseline` ASC),
  CONSTRAINT `fk_ProductRelease_CoreAssetBaseline1`
    FOREIGN KEY (`CoreAssetBaseline_idCoreAssetBaseline`)
    REFERENCES `olapCustoms`.`CoreAssetBaseline` (`idCoreAssetBaseline`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olapCustoms`.`Team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olapCustoms`.`Team` (
  `idTeam` INT NOT NULL,
  `name` VARCHAR(200) NULL,
  PRIMARY KEY (`idTeam`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olapCustoms`.`Developer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olapCustoms`.`Developer` (
  `idDeveloper` INT NOT NULL,
  `name` VARCHAR(200) NULL,
  `email` VARCHAR(200) NULL,
  `Team_idTeam` INT NOT NULL,
  PRIMARY KEY (`idDeveloper`),
  INDEX `fk_Developer_Team1_idx` (`Team_idTeam` ASC),
  CONSTRAINT `fk_Developer_Team1`
    FOREIGN KEY (`Team_idTeam`)
    REFERENCES `olapCustoms`.`Team` (`idTeam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olapCustoms`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olapCustoms`.`Customer` (
  `idCustomer` INT NOT NULL,
  `name` VARCHAR(200) NULL,
  PRIMARY KEY (`idCustomer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olapCustoms`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olapCustoms`.`Product` (
  `idProduct` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `Customer_idCustomer` INT NOT NULL,
  PRIMARY KEY (`idProduct`),
  INDEX `fk_Product_Customer1_idx` (`Customer_idCustomer` ASC),
  CONSTRAINT `fk_Product_Customer1`
    FOREIGN KEY (`Customer_idCustomer`)
    REFERENCES `olapCustoms`.`Customer` (`idCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olapCustoms`.`Purpose`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olapCustoms`.`Purpose` (
  `idPurpose` INT NOT NULL,
  `commitmessage` VARCHAR(200) NULL,
  `githubIssue` VARCHAR(200) NULL,
  `Product_idProduct` INT NOT NULL,
  PRIMARY KEY (`idPurpose`),
  INDEX `fk_Purpose_Product1_idx` (`Product_idProduct` ASC),
  CONSTRAINT `fk_Purpose_Product1`
    FOREIGN KEY (`Product_idProduct`)
    REFERENCES `olapCustoms`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olapCustoms`.`Customization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olapCustoms`.`Customization` (
  `idCustomization` INT NOT NULL,
  `newFeature` INT NULL,
  `newAsset` INT NULL,
  `linesAdded` VARCHAR(200) NULL,
  `linesDeleted` VARCHAR(200) NULL,
  `lineNumber` VARCHAR(200) NULL,
  `ProductAssetVP_idPV` INT NOT NULL,
  `ProductRelease_idProductRelease` INT NOT NULL,
  `Developer_idDeveloper` INT NOT NULL,
  `Purpose_idPurpose` INT NOT NULL,
  PRIMARY KEY (`idCustomization`),
  INDEX `fk_Customization_ProductAssetVP_idx` (`ProductAssetVP_idPV` ASC),
  INDEX `fk_Customization_ProductRelease1_idx` (`ProductRelease_idProductRelease` ASC),
  INDEX `fk_Customization_Developer1_idx` (`Developer_idDeveloper` ASC),
  INDEX `fk_Customization_Purpose1_idx` (`Purpose_idPurpose` ASC),
  CONSTRAINT `fk_Customization_ProductAssetVP`
    FOREIGN KEY (`ProductAssetVP_idPV`)
    REFERENCES `olapCustoms`.`ProductAssetVP` (`idPV`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Customization_ProductRelease1`
    FOREIGN KEY (`ProductRelease_idProductRelease`)
    REFERENCES `olapCustoms`.`ProductRelease` (`idProductRelease`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Customization_Developer1`
    FOREIGN KEY (`Developer_idDeveloper`)
    REFERENCES `olapCustoms`.`Developer` (`idDeveloper`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Customization_Purpose1`
    FOREIGN KEY (`Purpose_idPurpose`)
    REFERENCES `olapCustoms`.`Purpose` (`idPurpose`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
