-- MySQL Script generated by MySQL Workbench
-- Thu Aug 24 11:00:06 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SPLCustombd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SPLCustombd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SPLCustombd` DEFAULT CHARACTER SET utf8 ;
USE `SPLCustombd` ;

-- -----------------------------------------------------
-- Table `SPLCustombd`.`SPL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SPLCustombd`.`SPL` (
  `idSPL` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`idSPL`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SPLCustombd`.`CoreAssetBaseline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SPLCustombd`.`CoreAssetBaseline` (
  `idBaseline` VARCHAR(256) NOT NULL,
  `releaseDate` DATETIME NOT NULL,
  `SPL_idSPL` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`idBaseline`),
  INDEX `fk_CoreAssetBaseline_SPL1_idx` (`SPL_idSPL` ASC),
  CONSTRAINT `fk_CoreAssetBaseline_SPL1`
    FOREIGN KEY (`SPL_idSPL`)
    REFERENCES `SPLCustombd`.`SPL` (`idSPL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SPLCustombd`.`Feature`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SPLCustombd`.`Feature` (
  `idFeature` VARCHAR(256) NOT NULL,
  `name` VARCHAR(256) NULL,
  PRIMARY KEY (`idFeature`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SPLCustombd`.`CoreAsset`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SPLCustombd`.`CoreAsset` (
  `idCoreAsset` INT NOT NULL,
  `name` VARCHAR(256) NOT NULL,
  `path` VARCHAR(256) NOT NULL,
  `content` LONGTEXT NOT NULL,
  `size` INT NOT NULL,
  `CoreAssetBaseline_idBaseline` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`idCoreAsset`),
  INDEX `fk_CoreAsset_CoreAssetBaseline1_idx` (`CoreAssetBaseline_idBaseline` ASC),
  CONSTRAINT `fk_CoreAsset_CoreAssetBaseline1`
    FOREIGN KEY (`CoreAssetBaseline_idBaseline`)
    REFERENCES `SPLCustombd`.`CoreAssetBaseline` (`idBaseline`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SPLCustombd`.`ProductPortfolio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SPLCustombd`.`ProductPortfolio` (
  `idPortfolio` VARCHAR(256) NOT NULL,
  `SPL_idSPL` VARCHAR(256) NOT NULL,
  `CoreAssetBaseline_idBaseline` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`idPortfolio`),
  INDEX `fk_ProductPortfolio_SPL1_idx` (`SPL_idSPL` ASC),
  INDEX `fk_ProductPortfolio_CoreAssetBaseline1_idx` (`CoreAssetBaseline_idBaseline` ASC),
  CONSTRAINT `fk_ProductPortfolio_SPL1`
    FOREIGN KEY (`SPL_idSPL`)
    REFERENCES `SPLCustombd`.`SPL` (`idSPL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProductPortfolio_CoreAssetBaseline1`
    FOREIGN KEY (`CoreAssetBaseline_idBaseline`)
    REFERENCES `SPLCustombd`.`CoreAssetBaseline` (`idBaseline`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SPLCustombd`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SPLCustombd`.`Product` (
  `idProduct` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(256) NULL,
  `ProductPortfolio_idPortfolio` VARCHAR(256) NOT NULL,
  INDEX `fk_Product_ProductPortfolio1_idx` (`ProductPortfolio_idPortfolio` ASC),
  PRIMARY KEY (`idProduct`),
  CONSTRAINT `fk_Product_ProductPortfolio1`
    FOREIGN KEY (`ProductPortfolio_idPortfolio`)
    REFERENCES `SPLCustombd`.`ProductPortfolio` (`idPortfolio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SPLCustombd`.`ProductRelease`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SPLCustombd`.`ProductRelease` (
  `idRelease` VARCHAR(256) NOT NULL,
  `releaseDate` DATETIME NOT NULL,
  `Product_idProduct` INT NOT NULL,
  PRIMARY KEY (`idRelease`),
  INDEX `fk_ProductRelease_Product1_idx` (`Product_idProduct` ASC),
  CONSTRAINT `fk_ProductRelease_Product1`
    FOREIGN KEY (`Product_idProduct`)
    REFERENCES `SPLCustombd`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SPLCustombd`.`ProductAsset`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SPLCustombd`.`ProductAsset` (
  `idProductAsset` INT NOT NULL,
  `name` VARCHAR(256) NOT NULL,
  `path` VARCHAR(256) NOT NULL,
  `content` LONGTEXT NOT NULL,
  `size` INT NOT NULL,
  `ProductRelease_idRelease` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`idProductAsset`),
  INDEX `fk_ProductAsset_ProductRelease1_idx` (`ProductRelease_idRelease` ASC),
  CONSTRAINT `fk_ProductAsset_ProductRelease1`
    FOREIGN KEY (`ProductRelease_idRelease`)
    REFERENCES `SPLCustombd`.`ProductRelease` (`idRelease`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SPLCustombd`.`Customization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SPLCustombd`.`Customization` (
  `idCustomization` INT NOT NULL AUTO_INCREMENT,
  `operation` VARCHAR(256) NOT NULL,
  `CoreAsset_idCoreAsset` INT NULL,
  `ProductAsset_idProductAsset` INT NOT NULL,
  `Feature_idFeature` VARCHAR(256) NULL,
  `isNewFeature` INT,
  `isNewAsset` INT , 
  `featureNameModified` VARCHAR(256),

  PRIMARY KEY (`idCustomization`),
  INDEX `fk_Customization_CoreAsset1_idx` (`CoreAsset_idCoreAsset` ASC),
  INDEX `fk_Customization_ProductAsset1_idx` (`ProductAsset_idProductAsset` ASC),
  INDEX `fk_Customization_Feature1_idx` (`Feature_idFeature` ASC),
  CONSTRAINT `fk_Customization_CoreAsset1`
    FOREIGN KEY (`CoreAsset_idCoreAsset`)
    REFERENCES `SPLCustombd`.`CoreAsset` (`idCoreAsset`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Customization_ProductAsset1`
    FOREIGN KEY (`ProductAsset_idProductAsset`)
    REFERENCES `SPLCustombd`.`ProductAsset` (`idProductAsset`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Customization_Feature1`
    FOREIGN KEY (`Feature_idFeature`)
    REFERENCES `SPLCustombd`.`Feature` (`idFeature`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SPLCustombd`.`CoreAssetBaseline_has_Feature`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SPLCustombd`.`CoreAssetBaseline_has_Feature` (
  `CoreAssetBaseline_idBaseline` VARCHAR(256) NOT NULL,
  `Feature_idFeature` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`CoreAssetBaseline_idBaseline`, `Feature_idFeature`),
  INDEX `fk_CoreAssetBaseline_has_Feature_Feature1_idx` (`Feature_idFeature` ASC),
  INDEX `fk_CoreAssetBaseline_has_Feature_CoreAssetBaseline1_idx` (`CoreAssetBaseline_idBaseline` ASC),
  CONSTRAINT `fk_CoreAssetBaseline_has_Feature_CoreAssetBaseline1`
    FOREIGN KEY (`CoreAssetBaseline_idBaseline`)
    REFERENCES `SPLCustombd`.`CoreAssetBaseline` (`idBaseline`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CoreAssetBaseline_has_Feature_Feature1`
    FOREIGN KEY (`Feature_idFeature`)
    REFERENCES `SPLCustombd`.`Feature` (`idFeature`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SPLCustombd`.`CoreAsset_has_Feature`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SPLCustombd`.`CoreAsset_has_Feature` (
  `Feature_idFeature` VARCHAR(45) NOT NULL,
  `CoreAsset_idCoreAsset` INT NOT NULL,
  PRIMARY KEY (`Feature_idFeature`, `CoreAsset_idCoreAsset`),
  INDEX `fk_Feature_has_CoreAsset_CoreAsset1_idx` (`CoreAsset_idCoreAsset` ASC),
  INDEX `fk_Feature_has_CoreAsset_Feature1_idx` (`Feature_idFeature` ASC),
  CONSTRAINT `fk_Feature_has_CoreAsset_Feature1`
    FOREIGN KEY (`Feature_idFeature`)
    REFERENCES `SPLCustombd`.`Feature` (`idFeature`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Feature_has_CoreAsset_CoreAsset1`
    FOREIGN KEY (`CoreAsset_idCoreAsset`)
    REFERENCES `SPLCustombd`.`CoreAsset` (`idCoreAsset`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
