package org.onekin.customdiff.spldomain;

public enum  CustomizationType {
		
		CHANGE_IN_VARIATION_POINT_BODY,
		CHANGE_OUTSIDE_VARIATION_POINT,		
		
		NEW_VARIATION_POINT,
		NEW_VARIATION_POINT_WITH_NEW_FEATURES,
		
		REMOVE_VARIATION_POINT,
		
		MODIFIED_VARIATION_POINT_EXPRESSION,
		MODIFIED_VARIATION_POINT_EXPRESSION_WITH_NEWFEATURES,
		
		FEATURE_SCATTERING_MODIFICATION,
		FEATURE_TANGLING_MODIFICATION,

		NEW_ASSET_WITH_NO_VARIATIONPOINT,
		NEW_ASSET_WITH_VARIATIONPOINTS,
		NEW_ASSET_WITH_NEW_VARIATIONPOINT_AND_NEW_FEATURES;
	
}


